In [3]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from Herramientas import teselator as ts
import numpy as np
from math import exp as e
import seaborn as sns
import mpl_toolkits
%matplotlib inline
import random as rd
import random

ModuleNotFoundError: No module named 'seaborn'

In [4]:
inter ='D:\TESIS PHD ING TRANSPORTES\Investigación 1\Definitivo\Predios_Lineas\Lineas_Log_Macrozona\Lineas RM\inter_lineas_rm_549.shp'
inter = gpd.read_file(inter)

DriverError: D:\TESIS PHD ING TRANSPORTES\Investigación 1\Definitivo\Predios_Lineas\Lineas_Log_Macrozona\Lineas RM\inter_lineas_rm_549.shp: No such file or directory

In [3]:
display(inter)

,cell,area,COMUNA,MANZ_SII,NOM_COMUNA,CMN_MZ,AREA_1,layer,path,M2_Com_Lin,...,m2 prop. I,m2 prop. L,m2 prop. O,m2 prop. P,m2 prop. S,m2 prop. T,m2 prop. V,m2 prop. W,m2 prop. Z,geometry
0,63,785398.862217,14501,510,TALAGANTE,14501-510,2.097379e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,1646,...,468.484461,8.445637,43.966993,0.0,0.0,0.0,65.826290,0.0,0.000000,"POLYGON ((314246.090 6269141.778, 314362.431 6..."
1,146,785398.862217,14501,510,TALAGANTE,14501-510,2.097379e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,1646,...,625.931412,11.284023,58.743298,0.0,0.0,0.0,87.949005,0.0,0.000000,"POLYGON ((315045.665 6269661.500, 315187.158 6..."
2,147,785398.862217,14501,510,TALAGANTE,14501-510,2.097379e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,1646,...,329.674246,5.943226,30.939736,0.0,0.0,0.0,46.322203,0.0,0.000000,"POLYGON ((314362.431 6268940.269, 314912.249 6..."
3,228,785398.862217,14501,510,TALAGANTE,14501-510,2.097379e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,1646,...,691.593323,12.467748,64.905630,0.0,0.0,0.0,97.175096,0.0,0.000000,"POLYGON ((315859.241 6270156.971, 316011.886 6..."
4,229,785398.862217,14501,510,TALAGANTE,14501-510,2.097379e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,1646,...,770.477056,13.889830,72.308822,0.0,0.0,0.0,108.258971,0.0,0.000000,"POLYGON ((315187.158 6269416.426, 315736.977 6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66271,5335,785398.862217,15161,3024,LO BARNECHEA,15161-3024,1.063809e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,371,...,0.000000,18.309148,0.000000,0.0,0.0,0.0,127.553732,0.0,21.970978,"POLYGON ((366320.260 6307508.955, 366452.164 6..."
66272,5336,785398.862217,15161,3024,LO BARNECHEA,15161-3024,1.063809e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,371,...,0.000000,0.201029,0.000000,0.0,0.0,0.0,1.400505,0.0,0.241235,"POLYGON ((366689.539 6306556.642, 366862.550 6..."
66273,5418,785398.862217,15161,3024,LO BARNECHEA,15161-3024,1.063809e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,371,...,0.000000,2.391027,0.000000,0.0,0.0,0.0,16.657490,0.0,2.869233,"MULTIPOLYGON (((367647.482 6307032.798, 367418..."
66274,5419,785398.862217,15161,3024,LO BARNECHEA,15161-3024,1.063809e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,371,...,0.000000,4.771759,0.000000,0.0,0.0,0.0,33.243255,0.0,5.726111,"POLYGON ((367144.988 6307032.798, 367342.162 6..."
66275,5501,785398.862217,15161,3024,LO BARNECHEA,15161-3024,1.063809e+06,Manzanas_Santiago,D:/TESIS PHD ING TRANSPORTES/Investigación 1/I...,371,...,0.000000,0.183160,0.000000,0.0,0.0,0.0,1.276014,0.0,0.219792,"POLYGON ((367804.133 6306843.438, 367705.726 6..."

In [4]:
ciudad = (r'D:\TESIS PHD ING TRANSPORTES\Investigación 1\todo_menos1000.shp')
ciudad = gpd.read_file(ciudad)

In [5]:
#ciudad['UF'] = 15
display(ciudad)
ciudad.shape

,cell,area,M2_Com_Lin,M2_Hab_Lin,M2_Hot_Lin,M2_Ind_Lin,M2_Log_Lin,M2_Ofi_Lin,M2_Pub_Lin,M2_Sal_Lin,...,acc_ph,acc_pi,acc_pl,uf2018,lat,lon,aux,layer,path,geometry
0,3262,785398.862217,5179.029579,93345.811192,0.0,2284.970468,4270.169126,3095.806343,0.000000,0.000000,...,3.011574e+06,498577.600924,237810.131329,17.260151,345976.98300,6.305604e+06,0.013633,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((345702.074 6306080.485, 346251.892 6..."
1,3343,785398.862217,5364.611707,663.530776,0.0,3778.621151,7925.995131,5039.081269,0.000000,0.000000,...,1.875186e+06,371050.075199,225922.830361,17.260151,346801.71045,6.307033e+06,0.047340,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((346526.801 6307508.955, 347076.620 6..."
2,3344,785398.862217,4987.780126,54593.201512,0.0,24481.483122,48304.537574,30077.928620,0.000000,0.000000,...,2.546960e+06,411664.439956,238413.137324,17.260151,346801.71045,6.306080e+06,0.184049,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((346526.801 6306556.642, 347076.620 6..."
3,3428,785398.862217,4794.339606,99297.507143,0.0,10668.710089,7499.282436,7968.697350,986.465642,1485.083386,...,2.634732e+06,310564.607636,157660.098708,17.260151,347626.43790,6.305604e+06,0.162865,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((347351.529 6306080.485, 347901.347 6..."
4,3214,785398.862217,34.159033,396.166259,0.0,0.000000,277.591224,0.000000,0.000000,0.000000,...,3.009652e+05,56261.463750,25797.157764,5.000000,345152.25555,6.271797e+06,0.000000,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((344877.346 6272273.365, 345427.165 6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2440,5166,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((364670.805 6310365.895, 365220.624 6..."
2441,5167,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((364670.805 6309413.581, 365220.624 6..."
2442,5168,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((364670.805 6308461.268, 365220.624 6..."
2443,5252,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((365495.533 6307985.112, 366045.351 6..."
2444,5335,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((366320.260 6306556.642, 366045.351 6..."

(2445, 55)

In [6]:
ciudad.columns

Index(['cell', 'area', 'M2_Com_Lin', 'M2_Hab_Lin', 'M2_Hot_Lin', 'M2_Ind_Lin',
       'M2_Log_Lin', 'M2_Ofi_Lin', 'M2_Pub_Lin', 'M2_Sal_Lin', 'M2_Tra_Lin',
       'M2_Otr_Lin', 'M2_Eri_Lin', 'M2_Est_Lin', 'M2_Log10_L', 'M2_Com_Pre',
       'M2_Hab_Pre', 'M2_Hot_Pre', 'M2_Ind_Pre', 'M2_Log_Pre', 'M2_Ofi_Pre',
       'M2_Pub_Pre', 'M2_Sal_Pre', 'M2_Tra_Pre', 'M2_Otr_Pre', 'M2_Eri_Pre',
       'M2_Est_Pre', 'M2_Predios', 'M2_Pobla', 'M2_Lineas', 'Dist_Aero',
       'Dist_Cent', 'Dist_Metro', 'Dist_Auto', 'Dist_PGV', 'Dist_PSA',
       'D_Pre_Com', 'D_Lin_Com', 'Dist_Tren', 'acc_lc', 'acc_lh', 'acc_li',
       'acc_log10', 'acc_lof', 'acc_pc', 'acc_ph', 'acc_pi', 'acc_pl',
       'uf2018', 'lat', 'lon', 'aux', 'layer', 'path', 'geometry'],
      dtype='object')

In [7]:
display(ciudad)

,cell,area,M2_Com_Lin,M2_Hab_Lin,M2_Hot_Lin,M2_Ind_Lin,M2_Log_Lin,M2_Ofi_Lin,M2_Pub_Lin,M2_Sal_Lin,...,acc_ph,acc_pi,acc_pl,uf2018,lat,lon,aux,layer,path,geometry
0,3262,785398.862217,5179.029579,93345.811192,0.0,2284.970468,4270.169126,3095.806343,0.000000,0.000000,...,3.011574e+06,498577.600924,237810.131329,17.260151,345976.98300,6.305604e+06,0.013633,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((345702.074 6306080.485, 346251.892 6..."
1,3343,785398.862217,5364.611707,663.530776,0.0,3778.621151,7925.995131,5039.081269,0.000000,0.000000,...,1.875186e+06,371050.075199,225922.830361,17.260151,346801.71045,6.307033e+06,0.047340,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((346526.801 6307508.955, 347076.620 6..."
2,3344,785398.862217,4987.780126,54593.201512,0.0,24481.483122,48304.537574,30077.928620,0.000000,0.000000,...,2.546960e+06,411664.439956,238413.137324,17.260151,346801.71045,6.306080e+06,0.184049,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((346526.801 6306556.642, 347076.620 6..."
3,3428,785398.862217,4794.339606,99297.507143,0.0,10668.710089,7499.282436,7968.697350,986.465642,1485.083386,...,2.634732e+06,310564.607636,157660.098708,17.260151,347626.43790,6.305604e+06,0.162865,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((347351.529 6306080.485, 347901.347 6..."
4,3214,785398.862217,34.159033,396.166259,0.0,0.000000,277.591224,0.000000,0.000000,0.000000,...,3.009652e+05,56261.463750,25797.157764,5.000000,345152.25555,6.271797e+06,0.000000,todo2,D:/TESIS PHD ING TRANSPORTES/Investigación 1/D...,"POLYGON ((344877.346 6272273.365, 345427.165 6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2440,5166,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((364670.805 6310365.895, 365220.624 6..."
2441,5167,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((364670.805 6309413.581, 365220.624 6..."
2442,5168,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((364670.805 6308461.268, 365220.624 6..."
2443,5252,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((365495.533 6307985.112, 366045.351 6..."
2444,5335,785398.862217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,"POLYGON ((366320.260 6306556.642, 366045.351 6..."

In [8]:
ciudad.describe()

,cell,area,M2_Com_Lin,M2_Hab_Lin,M2_Hot_Lin,M2_Ind_Lin,M2_Log_Lin,M2_Ofi_Lin,M2_Pub_Lin,M2_Sal_Lin,...,acc_log10,acc_lof,acc_pc,acc_ph,acc_pi,acc_pl,uf2018,lat,lon,aux
count,2445.000000,2.445000e+03,2401.000000,2.401000e+03,2401.000000,2401.000000,2401.000000,2.401000e+03,2401.000000,2401.000000,...,2401.000000,2.401000e+03,2.401000e+03,2.401000e+03,2.401000e+03,2.401000e+03,2401.000000,2401.000000,2.401000e+03,2.401000e+03
mean,2866.262986,7.853989e+05,6520.037547,6.029907e+04,479.199455,5184.485545,7442.697220,5.526532e+03,498.825901,917.975506,...,99680.102202,8.215441e+04,2.059963e+05,1.721276e+06,3.427861e+05,1.408884e+05,10.484482,341869.833429,6.291304e+06,3.218949e+01
std,1077.055001,1.164391e-10,25198.946385,1.037819e+05,4519.941527,14206.168416,17996.797597,3.918579e+04,5798.361222,5783.243248,...,146494.500224,2.272755e+05,2.540515e+05,1.319470e+06,4.495442e+05,2.205400e+05,16.112868,10611.551596,1.800559e+04,8.958193e+02
min,63.000000,7.853989e+05,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,...,141.826882,2.082180e+01,1.736446e+02,5.205200e+03,6.172632e+02,1.356828e+02,0.200000,313812.612450,6.250846e+06,0.000000e+00
25%,2101.000000,7.853989e+05,13.401174,5.778575e+02,0.000000,0.000000,74.216357,1.054186e+01,0.000000,0.000000,...,7249.230874,2.399877e+03,3.698001e+04,6.167948e+05,4.662587e+04,8.825918e+03,0.200000,334430.798700,6.276083e+06,0.000000e+00
50%,2841.000000,7.853989e+05,303.979599,5.561374e+03,0.000000,179.893669,622.626159,1.884324e+02,0.000000,0.000000,...,27625.844547,1.000975e+04,1.051994e+05,1.309058e+06,1.666084e+05,4.035713e+04,3.000000,341853.345750,6.291320e+06,3.155878e-09
75%,3705.000000,7.853989e+05,3880.230815,9.938246e+04,0.000000,2235.780490,4688.955593,1.884065e+03,0.000000,106.704304,...,139266.663608,6.174664e+04,2.871203e+05,2.700200e+06,4.540847e+05,1.814446e+05,15.574789,350100.620250,6.306080e+06,2.393511e-05
max,5335.000000,7.853989e+05,669546.614855,1.055983e+06,137790.794331,153354.706325,197012.370080,1.273449e+06,153984.375807,107285.946417,...,818152.245245,2.557046e+06,1.817618e+06,5.197165e+06,2.943707e+06,1.322602e+06,220.000000,365770.441800,6.327984e+06,3.463103e+04

In [9]:
ciudad.columns

Index(['cell', 'area', 'M2_Com_Lin', 'M2_Hab_Lin', 'M2_Hot_Lin', 'M2_Ind_Lin',
       'M2_Log_Lin', 'M2_Ofi_Lin', 'M2_Pub_Lin', 'M2_Sal_Lin', 'M2_Tra_Lin',
       'M2_Otr_Lin', 'M2_Eri_Lin', 'M2_Est_Lin', 'M2_Log10_L', 'M2_Com_Pre',
       'M2_Hab_Pre', 'M2_Hot_Pre', 'M2_Ind_Pre', 'M2_Log_Pre', 'M2_Ofi_Pre',
       'M2_Pub_Pre', 'M2_Sal_Pre', 'M2_Tra_Pre', 'M2_Otr_Pre', 'M2_Eri_Pre',
       'M2_Est_Pre', 'M2_Predios', 'M2_Pobla', 'M2_Lineas', 'Dist_Aero',
       'Dist_Cent', 'Dist_Metro', 'Dist_Auto', 'Dist_PGV', 'Dist_PSA',
       'D_Pre_Com', 'D_Lin_Com', 'Dist_Tren', 'acc_lc', 'acc_lh', 'acc_li',
       'acc_log10', 'acc_lof', 'acc_pc', 'acc_ph', 'acc_pi', 'acc_pl',
       'uf2018', 'lat', 'lon', 'aux', 'layer', 'path', 'geometry'],
      dtype='object')

In [10]:
bd_predios = (r'D:\TESIS PHD ING TRANSPORTES\Investigación 1\BRORGA2441_NAC_2021_1\BRORGA2441N_NAC_2021_1.csv')
predios = pd.read_csv(bd_predios, sep='|', header=None,encoding='latin1',low_memory=False)

In [11]:
predios.columns = ['Comuna','Manzana','Predial','Dirección','Avalúo fiscal','Contribución semestral','Código de destino','Avalúo exento','Comuna Rol Bien Común 1','Manzana Rol Bien Común 1','Predio Rol Bien Común 1','Comuna Rol Bien Común 2','Manzana Rol Bien Común 2','Predio Rol Bien Común 2', 'Superficie (m2)']

In [12]:
predios.rename(columns={"Superficie (m2)": "Sup_Predial", "Avalúo fiscal": "Avaluo"}, inplace = True)

In [13]:
num=[13101,13101,13134,13135,13159,13167,14107,14109,14111,14113,14114,14127,14155,14156,14157,14158,14166,14201,14202,14203,14501,14502,14503,14504,14505,14601,14602,14603,14604,14605,15103,15105,15108,15128,15132,15151,15152,15160,15161,16106,16110,16131,16153,16154,16162,16163,16164,16165,16301,16302,16303,16401,16402,16403,16404]
predios_rm = predios[predios['Comuna'].isin(num)]

In [14]:
predios_rm['CMN_MZ'] = predios_rm.apply(lambda row: str(row['Comuna'])+'-'+str(row['Manzana']),axis=1)
predios_rm['CMN_MZ_PR'] = predios_rm.apply(lambda row: str(row['Comuna'])+'-'+str(row['Manzana'])+'-'+str(row['Predial']),axis=1)
predios_rm.head(1)

<ipython-input-14-451699e3b761>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predios_rm['CMN_MZ'] = predios_rm.apply(lambda row: str(row['Comuna'])+'-'+str(row['Manzana']),axis=1)
<ipython-input-14-451699e3b761>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predios_rm['CMN_MZ_PR'] = predios_rm.apply(lambda row: str(row['Comuna'])+'-'+str(row['Manzana'])+'-'+str(row['Predial']),axis=1)

,Comuna,Manzana,Predial,Dirección,Avaluo,Contribución semestral,Código de destino,Avalúo exento,Comuna Rol Bien Común 1,Manzana Rol Bien Común 1,Predio Rol Bien Común 1,Comuna Rol Bien Común 2,Manzana Rol Bien Común 2,Predio Rol Bien Común 2,Sup_Predial,CMN_MZ,CMN_MZ_PR
4135260,13101,1,1,ALAMEDA LIB. B. OHIGGINS 3 LC 1,85202051,474150,C,0,13101,1,90001,0,0,0,0,13101-1,13101-1-1

In [15]:
predios_rm2 = predios_rm[['CMN_MZ_PR','CMN_MZ','Avaluo','Dirección','Sup_Predial']]
predios_rm2.head(5)

,CMN_MZ_PR,CMN_MZ,Avaluo,Dirección,Sup_Predial
4135260,13101-1-1,13101-1,85202051,ALAMEDA LIB. B. OHIGGINS 3 LC 1,0
4135261,13101-1-2,13101-1,41527285,ALAMEDA LIB. B. OHIGGINS 9,0
4135262,13101-1-3,13101-1,42523449,ALAMEDA LIB. B. OHIGGINS 15,0
4135263,13101-1-4,13101-1,62201745,ALAMEDA LIB. B. OHIGGINS 75,0
4135264,13101-1-5,13101-1,139102111,ALAMEDA LIB. B. OHIGGINS 77,0

In [16]:
#bd_lineas = (path + 'lineas_construccion.csv')
bd_lineas = (r'D:\TESIS PHD ING TRANSPORTES\Investigación 1\BRORGA2441_NAC_2021_1\BRORGA2441NL_NAC_2021_1.csv')
lineas = pd.read_csv(bd_lineas, sep='|', header=None,encoding='latin1',low_memory=False)

In [17]:
lineas.columns = ['Comuna','Manzana','Predial','Linea','Material','Calidad','Año','Superficie (m2)','Código de destino','Especial']

In [18]:
num=[13101,13101,13134,13135,13159,13167,14107,14109,14111,14113,14114,14127,14155,14156,14157,14158,14166,14201,14202,14203,14501,14502,14503,14504,14505,14601,14602,14603,14604,14605,15103,15105,15108,15128,15132,15151,15152,15160,15161,16106,16110,16131,16153,16154,16162,16163,16164,16165,16301,16302,16303,16401,16402,16403,16404]
lineas_rm=lineas[lineas['Comuna'].isin(num)]

In [19]:
lineas_rm2 = lineas_rm.copy()
lineas_rm2['CMN_MZ'] = lineas_rm2.apply(lambda row: str(row['Comuna'])+'-'+str(row['Manzana']),axis=1)
lineas_rm2['CMN_MZ_PR'] = lineas_rm2.apply(lambda row: str(row['Comuna'])+'-'+str(row['Manzana'])+'-'+str(row['Predial']),axis=1)
display(lineas_rm2)

,Comuna,Manzana,Predial,Linea,Material,Calidad,Año,Superficie (m2),Código de destino,Especial,CMN_MZ,CMN_MZ_PR
5420028,13101,1,1,1,B,3,1955,64,C,NaN,13101-1,13101-1-1
5420029,13101,1,1,2,B,3,1955,54,C,NaN,13101-1,13101-1-1
5420030,13101,1,1,3,B,3,1955,64,C,SB,13101-1,13101-1-1
5420031,13101,1,2,1,B,3,1955,32,C,NaN,13101-1,13101-1-2
5420032,13101,1,2,2,B,3,1955,32,O,NaN,13101-1,13101-1-2
...,...,...,...,...,...,...,...,...,...,...,...,...
9867921,16404,90160,6,2,GC,2,1950,520,L,NaN,16404-90160,16404-90160-6
9867922,16404,90160,6,3,GC,2,1962,240,V,NaN,16404-90160,16404-90160-6
9867923,16404,90160,6,4,C,4,1962,25,T,NaN,16404-90160,16404-90160-6
9867924,16404,90160,6,5,E,4,1962,12,V,NaN,16404-90160,16404-90160-6
9867925,16404,90160,6,6,C,4,2002,59,V,NaN,16404-90160,16404-90160-6

In [20]:
#lineas_rm2=lineas_rm_L["Superficie (m2)"].between(10, 100000000, inclusive=False)
#lineas_rm_L = lineas_rm_L[lineas_rm2]
#display(lineas_rm_L)

In [21]:
def juntar_df_sinrep(df1, df2, on):
  columns1 = list(df1.columns)
  columns2 = list(df2.columns)
  columns2_sr = [c for c in columns2 if c not in columns1]
  columns2_sr.append(on)
  return pd.merge(df1, df2[columns2_sr], on = on)

In [22]:
junta = juntar_df_sinrep(lineas_rm2, predios_rm2, on = 'CMN_MZ_PR') #tambien puede ser por lineas_rm_L
display(junta)

,Comuna,Manzana,Predial,Linea,Material,Calidad,Año,Superficie (m2),Código de destino,Especial,CMN_MZ,CMN_MZ_PR,Avaluo,Dirección,Sup_Predial
0,13101,1,1,1,B,3,1955,64,C,NaN,13101-1,13101-1-1,85202051,ALAMEDA LIB. B. OHIGGINS 3 LC 1,0
1,13101,1,1,2,B,3,1955,54,C,NaN,13101-1,13101-1-1,85202051,ALAMEDA LIB. B. OHIGGINS 3 LC 1,0
2,13101,1,1,3,B,3,1955,64,C,SB,13101-1,13101-1-1,85202051,ALAMEDA LIB. B. OHIGGINS 3 LC 1,0
3,13101,1,2,1,B,3,1955,32,C,NaN,13101-1,13101-1-2,41527285,ALAMEDA LIB. B. OHIGGINS 9,0
4,13101,1,2,2,B,3,1955,32,O,NaN,13101-1,13101-1-2,41527285,ALAMEDA LIB. B. OHIGGINS 9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4447893,16404,90160,6,2,GC,2,1950,520,L,NaN,16404-90160,16404-90160-6,763187291,ESTACION PAINE,98055
4447894,16404,90160,6,3,GC,2,1962,240,V,NaN,16404-90160,16404-90160-6,763187291,ESTACION PAINE,98055
4447895,16404,90160,6,4,C,4,1962,25,T,NaN,16404-90160,16404-90160-6,763187291,ESTACION PAINE,98055
4447896,16404,90160,6,5,E,4,1962,12,V,NaN,16404-90160,16404-90160-6,763187291,ESTACION PAINE,98055
4447897,16404,90160,6,6,C,4,2002,59,V,NaN,16404-90160,16404-90160-6,763187291,ESTACION PAINE,98055

In [23]:
#junta.to_csv('junta050521.csv')

# AQUÍ

In [24]:
#lin_con = junta.copy()

# Condiciones

#ano_inicio = 2018 #cambiar 2015
#ano_fin = 2020
#sup = 1

#bool_ano_i = (lin_con['Año'] >= ano_inicio)
#bool_ano_f = (lin_con['Año'] <= ano_fin)
#bool_uso_suelo = (lin_con['Código de destino'] == 'L') #Logístico
#bool_sup = (lin_con['Sup_Predial'] >= sup)

#bool_total = bool_ano_i & bool_ano_f & bool_sup #& #& bool_uso_suelo 

#lin_con = lin_con.loc[bool_total]

In [25]:
lin_con = junta.copy()

# Condiciones

ano_inicio = 2016 #cambiar 2015
ano_fin = 2020
sup_pre = 1
sup_lin = 10

bool_ano_i = (lin_con['Año'] >= ano_inicio)
bool_ano_f = (lin_con['Año'] <= ano_fin)
bool_uso_suelo = (lin_con['Código de destino'] == 'L') #Logístico
bool_sup_pre = (lin_con['Sup_Predial'] >= sup_pre)
bool_sup_lin = (lin_con['Superficie (m2)'] >= sup_lin)
bool_cat = (lin_con['Calidad'] == 1)

bool_total = bool_ano_i & bool_ano_f & bool_uso_suelo & bool_sup_pre #& bool_sup_lin  #& bool_cat 

lin_con = lin_con.loc[bool_total]

In [26]:
#lin_con.to_csv('bbdd_logistica_10m2.csv')

In [27]:
#lin_con.to_csv('bbdd_todo_usos_2016_2020.csv')

In [28]:
#lin_con['cat_hogar'] = lin_con.apply(lambda row: 1 if (row['Calidad'] <= 2) else 2 if (row['Calidad'] <= 3) else 3 , axis = 1)

In [29]:
#lin_con['valor_prop'] = ((lin_con['Avaluo'] / lin_con['Superficie (m2)'])*29500)*0.3

In [30]:
display(lin_con)

,Comuna,Manzana,Predial,Linea,Material,Calidad,Año,Superficie (m2),Código de destino,Especial,CMN_MZ,CMN_MZ_PR,Avaluo,Dirección,Sup_Predial
24783,13101,96,90001,4,B,4,2017,3092,L,SB,13101-96,13101-96-90001,10297224805,TUCAPEL JIMENEZ 136,2289
26979,13101,101,552,3,B,4,2017,1069,L,SB,13101-101,13101-101-552,8410517340,HUERFANOS 840,810
27343,13101,101,947,3,B,4,2017,1723,L,SB,13101-101,13101-101-947,45517870644,HUERFANOS 824 - 830 - 836,2574
41965,13101,138,16,6,B,4,2016,113,L,SB,13101-138,13101-138-16,1867599275,TEATINOS 340,410
70401,13101,187,224,3,B,4,2018,274,L,SB,13101-187,13101-187-224,4732981702,STO DOMINGO 1114,972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4441040,16404,1769,91,2,E,4,2019,21,L,NaN,16404-1769,16404-1769-91,28357295,PINTUE PC 37 LT 5,5000
4441481,16404,1814,53,5,E,5,2019,6,L,NaN,16404-1814,16404-1814-53,121138024,RANGUE PC 10 LT 10 J,6000
4441509,16404,1823,116,4,G,3,2019,8,L,NaN,16404-1823,16404-1823-116,61956482,BELLOTOS ACULEO PC 20,5000
4441559,16404,1826,85,1,E,4,2018,36,L,NaN,16404-1826,16404-1826-85,22223841,HJ NORTE RVA CORA 2 PC 6 LT 43,5381
4441628,16404,1900,128,3,E,5,2018,18,L,NaN,16404-1900,16404-1900-128,26021060,EL ALAMO RESTO PC 1 ST 1 A 19,5000

In [31]:
lin_con.drop_duplicates('CMN_MZ_PR', keep="first", inplace=True)

In [32]:
display(lin_con)

,Comuna,Manzana,Predial,Linea,Material,Calidad,Año,Superficie (m2),Código de destino,Especial,CMN_MZ,CMN_MZ_PR,Avaluo,Dirección,Sup_Predial
24783,13101,96,90001,4,B,4,2017,3092,L,SB,13101-96,13101-96-90001,10297224805,TUCAPEL JIMENEZ 136,2289
26979,13101,101,552,3,B,4,2017,1069,L,SB,13101-101,13101-101-552,8410517340,HUERFANOS 840,810
27343,13101,101,947,3,B,4,2017,1723,L,SB,13101-101,13101-101-947,45517870644,HUERFANOS 824 - 830 - 836,2574
41965,13101,138,16,6,B,4,2016,113,L,SB,13101-138,13101-138-16,1867599275,TEATINOS 340,410
70401,13101,187,224,3,B,4,2018,274,L,SB,13101-187,13101-187-224,4732981702,STO DOMINGO 1114,972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4441040,16404,1769,91,2,E,4,2019,21,L,NaN,16404-1769,16404-1769-91,28357295,PINTUE PC 37 LT 5,5000
4441481,16404,1814,53,5,E,5,2019,6,L,NaN,16404-1814,16404-1814-53,121138024,RANGUE PC 10 LT 10 J,6000
4441509,16404,1823,116,4,G,3,2019,8,L,NaN,16404-1823,16404-1823-116,61956482,BELLOTOS ACULEO PC 20,5000
4441559,16404,1826,85,1,E,4,2018,36,L,NaN,16404-1826,16404-1826-85,22223841,HJ NORTE RVA CORA 2 PC 6 LT 43,5381
4441628,16404,1900,128,3,E,5,2018,18,L,NaN,16404-1900,16404-1900-128,26021060,EL ALAMO RESTO PC 1 ST 1 A 19,5000

In [33]:
#bd1 = juntar_df_sinrep(inter, ciudad, on = 'cell')

In [34]:
#display(bd1)

In [35]:
bd1 = ('D:\TESIS PHD ING TRANSPORTES\Investigación 1\ciudad_inter.shp')
bd1 = gpd.read_file(bd1)

In [36]:
bd1.columns

Index(['cell', 'area', 'M2_Com_Lin', 'M2_Hab_Lin', 'M2_Hot_Lin', 'M2_Ind_Lin',
       'M2_Log_Lin', 'M2_Ofi_Lin', 'M2_Pub_Lin', 'M2_Sal_Lin', 'M2_Tra_Lin',
       'M2_Otr_Lin', 'M2_Eri_Lin', 'M2_Est_Lin', 'M2_Log10_L', 'M2_Com_Pre',
       'M2_Hab_Pre', 'M2_Hot_Pre', 'M2_Ind_Pre', 'M2_Log_Pre', 'M2_Ofi_Pre',
       'M2_Pub_Pre', 'M2_Sal_Pre', 'M2_Tra_Pre', 'M2_Otr_Pre', 'M2_Eri_Pre',
       'M2_Est_Pre', 'M2_Predios', 'M2_Pobla', 'M2_Lineas', 'Dist_Aero',
       'Dist_Cent', 'Dist_Metro', 'Dist_Auto', 'Dist_PGV', 'Dist_PSA',
       'D_Pre_Com', 'D_Lin_Com', 'Dist_Tren', 'acc_lc', 'acc_lh', 'acc_li',
       'acc_log10', 'acc_lof', 'acc_pc', 'acc_ph', 'acc_pi', 'acc_pl',
       'uf2018', 'lat', 'lon', 'aux', 'layer', 'path', 'cell_2', 'area_2',
       'COMUNA', 'MANZ_SII', 'NOM_COMUNA', 'CMN_MZ', 'AREA_1', 'layer_2',
       'path_2', 'geometry'],
      dtype='object')

In [37]:
bd2 = juntar_df_sinrep(bd1, lin_con, on = 'CMN_MZ')

In [38]:
bd2.columns

Index(['cell', 'area', 'M2_Com_Lin', 'M2_Hab_Lin', 'M2_Hot_Lin', 'M2_Ind_Lin',
       'M2_Log_Lin', 'M2_Ofi_Lin', 'M2_Pub_Lin', 'M2_Sal_Lin', 'M2_Tra_Lin',
       'M2_Otr_Lin', 'M2_Eri_Lin', 'M2_Est_Lin', 'M2_Log10_L', 'M2_Com_Pre',
       'M2_Hab_Pre', 'M2_Hot_Pre', 'M2_Ind_Pre', 'M2_Log_Pre', 'M2_Ofi_Pre',
       'M2_Pub_Pre', 'M2_Sal_Pre', 'M2_Tra_Pre', 'M2_Otr_Pre', 'M2_Eri_Pre',
       'M2_Est_Pre', 'M2_Predios', 'M2_Pobla', 'M2_Lineas', 'Dist_Aero',
       'Dist_Cent', 'Dist_Metro', 'Dist_Auto', 'Dist_PGV', 'Dist_PSA',
       'D_Pre_Com', 'D_Lin_Com', 'Dist_Tren', 'acc_lc', 'acc_lh', 'acc_li',
       'acc_log10', 'acc_lof', 'acc_pc', 'acc_ph', 'acc_pi', 'acc_pl',
       'uf2018', 'lat', 'lon', 'aux', 'layer', 'path', 'cell_2', 'area_2',
       'COMUNA', 'MANZ_SII', 'NOM_COMUNA', 'CMN_MZ', 'AREA_1', 'layer_2',
       'path_2', 'geometry', 'Comuna', 'Manzana', 'Predial', 'Linea',
       'Material', 'Calidad', 'Año', 'Superficie (m2)', 'Código de destino',
       'Especial', 'CMN_MZ_PR', 'Avaluo', 'Dirección', 'Sup_Predial'],
      dtype='object')

In [39]:
bd2['valor_prop'] = bd2['Sup_Predial'] * bd2['uf2018']

In [40]:
bd2['Ratio_Pre'] = bd2['Sup_Predial'] / bd2['M2_Predios']

In [41]:
#bd_localizaciones = bd1[['cell', 'CMN_MZ','Avalúo fiscal', 'Superficie (m2)', 'Calidad construcción', 'Manzana', 'Año construcción']]

bd_localizaciones = bd2[['cell', 'CMN_MZ_PR', 'Avaluo', 'Superficie (m2)', 'Sup_Predial','Calidad','Año',
                'Código de destino','Comuna', 'Predial','Linea',
                'M2_Predios', 'M2_Pobla',
                'acc_lc', 'acc_lh', 'acc_li', 'acc_log10',  'acc_lof','acc_pc', 'acc_ph', 'acc_pi', 'acc_pl',
                'Dist_Cent', 'Dist_Metro', 'Dist_Auto', 'Dist_PGV', 'Dist_PSA','D_Pre_Com', 'D_Lin_Com', 'Dist_Tren',
                         'uf2018','valor_prop', 'Ratio_Pre']]

display(bd_localizaciones)

,cell,CMN_MZ_PR,Avaluo,Superficie (m2),Sup_Predial,Calidad,Año,Código de destino,Comuna,Predial,...,Dist_Metro,Dist_Auto,Dist_PGV,Dist_PSA,D_Pre_Com,D_Lin_Com,Dist_Tren,uf2018,valor_prop,Ratio_Pre
0,3343,14158-3130-19,5666426720,63,62070,4,2017,L,14158,19,...,2904.777042,1509.101718,1.107709,1.065729,0.096482,0.089667,0.105891,17.260151,1.071338e+06,0.284820
1,3343,14158-3130-190,125039341491,852,186177,4,2016,L,14158,190,...,2904.777042,1509.101718,1.107709,1.065729,0.096482,0.089667,0.105891,17.260151,3.213443e+06,0.854309
2,3090,14158-3130-19,5666426720,63,62070,4,2017,L,14158,19,...,7728.527688,2175.862554,1.158828,1.133505,0.199706,0.206103,0.206829,1.700000,1.055190e+05,0.770294
3,3090,14158-3130-190,125039341491,852,186177,4,2016,L,14158,190,...,7728.527688,2175.862554,1.158828,1.133505,0.199706,0.206103,0.206829,1.700000,3.165009e+05,2.310473
4,3256,14158-3130-19,5666426720,63,62070,4,2017,L,14158,19,...,7268.110772,2623.165139,1.175288,1.149965,0.199737,0.187224,0.209479,1.700000,1.055190e+05,4.096459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3203,3377,16403-1015-65,87357450,15,5430,4,2018,L,16403,65,...,10333.912017,1318.146483,1.225241,0.924216,0.223700,0.227752,0.234881,0.200000,1.086000e+03,0.219922
3204,3460,16403-1015-65,87357450,15,5430,4,2018,L,16403,65,...,9448.598744,2212.829398,1.233012,0.931987,0.231471,0.235523,0.242652,0.200000,1.086000e+03,0.488966
3205,4371,16302-172-25,62743724,30,5068,4,2017,L,16302,25,...,6943.715420,6298.117816,1.298205,1.040873,0.262490,0.246731,0.276414,0.200000,1.013600e+03,0.170052
3206,5335,15161-3024-37,94358606,17,16600,5,2017,L,15161,37,...,NaN,NaN,NaN,NaN,0.243855,0.231298,NaN,NaN,NaN,NaN
3207,5335,15161-3024-57,98471749,13,15050,5,2017,L,15161,57,...,NaN,NaN,NaN,NaN,0.243855,0.231298,NaN,NaN,NaN,NaN

In [42]:
bd_localizaciones.columns

Index(['cell', 'CMN_MZ_PR', 'Avaluo', 'Superficie (m2)', 'Sup_Predial',
       'Calidad', 'Año', 'Código de destino', 'Comuna', 'Predial', 'Linea',
       'M2_Predios', 'M2_Pobla', 'acc_lc', 'acc_lh', 'acc_li', 'acc_log10',
       'acc_lof', 'acc_pc', 'acc_ph', 'acc_pi', 'acc_pl', 'Dist_Cent',
       'Dist_Metro', 'Dist_Auto', 'Dist_PGV', 'Dist_PSA', 'D_Pre_Com',
       'D_Lin_Com', 'Dist_Tren', 'uf2018', 'valor_prop', 'Ratio_Pre'],
      dtype='object')

In [43]:
bd_localizaciones.rename(columns={"Superficie (m2)": "Sup_Lineas", "Avalúo fiscal": "Avaluo"}, inplace = True)

C:\Users\guret\miniconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [44]:
bd_localizaciones.drop_duplicates('CMN_MZ_PR', keep="first", inplace=True)

<ipython-input-44-5a0860dc8609>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bd_localizaciones.drop_duplicates('CMN_MZ_PR', keep="first", inplace=True)

In [45]:
#bd_localizaciones_L = bd_localizaciones.loc[bd_localizaciones['Código de destino'] == 'L']
#bd_localizaciones_L.shape

In [46]:
bd_localizaciones_L = bd_localizaciones.copy()

ano_inicio = 2018 #cambiar 2015
ano_fin = 2020
sup_min = 2501
sup_max = 10000

bool_ano_i = (bd_localizaciones_L['Año'] >= ano_inicio)
bool_ano_f = (bd_localizaciones_L['Año'] <= ano_fin)
bool_uso_suelo = (bd_localizaciones_L['Código de destino'] == 'L') #Logístico
bool_sup_min = (bd_localizaciones_L['Sup_Predial'] <= sup_min)
bool_sup_max = (bd_localizaciones_L['Sup_Predial'] <= sup_max)

bool_total = bool_ano_i & bool_ano_f #& bool_uso_suelo & bool_sup_min & bool_sup_max

bd_localizaciones_L = bd_localizaciones_L.loc[bool_total]

In [47]:
display(bd_localizaciones_L)

,cell,CMN_MZ_PR,Avaluo,Sup_Lineas,Sup_Predial,Calidad,Año,Código de destino,Comuna,Predial,...,Dist_Metro,Dist_Auto,Dist_PGV,Dist_PSA,D_Pre_Com,D_Lin_Com,Dist_Tren,uf2018,valor_prop,Ratio_Pre
56,3344,14158-3120-157,530824273,141,2050,3,2018,L,14158,157,...,1968.884417,647.791839,1.111346,1.061928,0.092665,0.085727,0.102090,17.260151,35383.309969,0.004044
118,4001,15161-3814-309,458003745,34,1233,4,2019,L,15161,309,...,10484.134931,4747.918149,1.267957,1.188101,0.218521,0.205965,0.228263,10.000000,12330.000000,0.004359
696,3089,14201-1386-160,255604867,29,942,4,2019,L,14201,160,...,8617.967124,1892.185202,1.151557,1.126235,0.192435,0.198833,0.199559,1.700000,1601.400000,0.003490
761,3333,14201-1324-49,271968487,7,2000,4,2018,L,14201,49,...,12402.873293,2483.948785,1.179351,1.157484,0.226720,0.233117,0.233843,2.000000,4000.000000,0.002647
824,2337,14202-197-63,186195638,554,840,2,2019,L,14202,63,...,15340.616256,1002.201092,1.086016,1.117339,0.203899,0.213940,0.203474,1.800000,1512.000000,0.003846
825,2337,14202-197-69,135582043,82,935,4,2019,L,14202,69,...,15340.616256,1002.201092,1.086016,1.117339,0.203899,0.213940,0.203474,1.800000,1683.000000,0.004280
826,2337,14202-197-80,141212206,730,1230,3,2019,L,14202,80,...,15340.616256,1002.201092,1.086016,1.117339,0.203899,0.213940,0.203474,1.800000,2214.000000,0.005631
827,2337,14202-197-85,225648450,600,1234,3,2018,L,14202,85,...,15340.616256,1002.201092,1.086016,1.117339,0.203899,0.213940,0.203474,1.800000,2221.200000,0.005649
1033,4441,15128-6950-408,171750959,90,1957,3,2019,L,15128,408,...,5516.438719,5407.916786,1.200884,1.068139,0.152957,0.137198,0.166881,15.000000,29355.000000,0.004029
1035,4441,15128-6950-465,18659153,37,1000,4,2019,L,15128,465,...,5516.438719,5407.916786,1.200884,1.068139,0.152957,0.137198,0.166881,15.000000,15000.000000,0.002059
1110,3946,15128-2801-89,65873018,9,420,4,2019,L,15128,89,...,370.488331,2428.564932,1.166224,1.006670,0.128507,0.112748,0.142430,20.000000,8400.000000,0.000747
1196,4023,15152-9690-25,36264111,9,143,4,2019,L,15152,25,...,888.493726,880.018891,1.155103,1.032452,0.101643,0.085884,0.115567,35.000000,5005.000000,0.000272
1476,2364,14109-74-11,452928035,430,1200,3,2019,L,14109,11,...,154.225771,1592.666292,1.032096,0.873047,0.112511,0.132829,0.096982,17.000000,20400.000000,0.002121
1482,2532,14109-925-91,146491418,42,2000,4,2018,L,14109,91,...,2515.321617,2313.100019,1.057618,0.878543,0.111910,0.132228,0.102296,3.500000,7000.000000,0.003190
1485,2532,14109-925-145,203007027,461,2081,3,2018,L,14109,145,...,2515.321617,2313.100019,1.057618,0.878543,0.111910,0.132228,0.102296,3.500000,7283.500000,0.003319
1538,2121,14109-6024-45,45764304,5,128,4,2019,L,14109,45,...,5648.799176,4323.779198,1.093240,0.824961,0.170312,0.190629,0.160698,14.000000,1792.000000,0.000268
1540,3035,16165-14108-9,303161399,670,2022,3,2019,L,16165,9,...,4193.750526,2444.547976,1.135049,0.915036,0.129846,0.133916,0.141028,14.000000,28308.000000,0.002164
2005,2272,14111-2580-621,26983228,38,279,4,2019,L,14111,621,...,2810.213138,1474.866124,0.980819,0.955497,0.105294,0.119986,0.088987,23.827678,6647.922250,0.000680
2169,4038,16301-2980-93,131181381,192,2496,3,2018,L,16301,93,...,5132.961926,3116.400810,1.246139,1.000943,0.210424,0.194665,0.224347,3.000000,7488.000000,0.006490
2170,4038,16301-2980-234,244444091,450,2463,3,2018,L,16301,234,...,5132.961926,3116.400810,1.246139,1.000943,0.210424,0.194665,0.224347,3.000000,7389.000000,0.006405
2370,3276,16106-4765-4,84240144,8,415,4,2019,L,16106,4,...,515.531047,616.778689,1.085701,0.960676,0.049470,0.059170,0.060256,32.831032,13624.878095,0.000790
2371,3603,15105-4-2,145613844,6,274,3,2018,L,15105,2,...,757.561634,2449.217794,1.099678,1.000284,0.036358,0.016495,0.056835,43.212955,11840.349761,0.000521
2628,2267,14111-7761-96,391159180,187,1635,3,2018,L,14111,96,...,6933.240200,310.626607,1.004088,0.978766,0.120026,0.131777,0.109875,16.590211,27124.994252,0.005429
2719,3612,16131-3120-35,68479802,158,540,3,2018,L,16131,35,...,1342.511183,610.997030,1.135949,0.983250,0.097918,0.085386,0.111536,30.938140,16706.595579,0.000996
2720,3445,16153-9-37,44951247,136,835,3,2019,L,16153,37,...,1823.821622,1937.253094,1.120026,0.969720,0.082684,0.078421,0.096283,27.759991,23179.592151,0.001436
2722,3188,13134-860-26,1033868574,544,1269,4,2018,L,13134,26,...,919.082233,900.503076,1.061588,0.965155,0.009618,0.029935,0.021276,31.198403,39590.773172,0.001344
2737,970,14501-502-101,35211823,12,1000,4,2018,L,14501,101,...,20905.881506,2033.211223,1.141177,0.685213,0.302921,0.323238,0.293307,0.200000,200.000000,0.005241

In [48]:
bd_localizaciones_L = bd_localizaciones_L.sample(n=4)
display(bd_localizaciones_L)

,cell,CMN_MZ_PR,Avaluo,Sup_Lineas,Sup_Predial,Calidad,Año,Código de destino,Comuna,Predial,...,Dist_Metro,Dist_Auto,Dist_PGV,Dist_PSA,D_Pre_Com,D_Lin_Com,Dist_Tren,uf2018,valor_prop,Ratio_Pre
2722,3188,13134-860-26,1033868574,544,1269,4,2018,L,13134,26,...,919.082233,900.503076,1.061588,0.965155,0.009618,0.029935,0.021276,31.198403,39590.773172,0.001344
825,2337,14202-197-69,135582043,82,935,4,2019,L,14202,69,...,15340.616256,1002.201092,1.086016,1.117339,0.203899,0.213940,0.203474,1.800000,1683.000000,0.004280
2719,3612,16131-3120-35,68479802,158,540,3,2018,L,16131,35,...,1342.511183,610.997030,1.135949,0.983250,0.097918,0.085386,0.111536,30.938140,16706.595579,0.000996
2628,2267,14111-7761-96,391159180,187,1635,3,2018,L,14111,96,...,6933.240200,310.626607,1.004088,0.978766,0.120026,0.131777,0.109875,16.590211,27124.994252,0.005429

In [49]:
max_mz = bd_localizaciones_L.sample(n=4)
display(bd_localizaciones_L)

,cell,CMN_MZ_PR,Avaluo,Sup_Lineas,Sup_Predial,Calidad,Año,Código de destino,Comuna,Predial,...,Dist_Metro,Dist_Auto,Dist_PGV,Dist_PSA,D_Pre_Com,D_Lin_Com,Dist_Tren,uf2018,valor_prop,Ratio_Pre
2722,3188,13134-860-26,1033868574,544,1269,4,2018,L,13134,26,...,919.082233,900.503076,1.061588,0.965155,0.009618,0.029935,0.021276,31.198403,39590.773172,0.001344
825,2337,14202-197-69,135582043,82,935,4,2019,L,14202,69,...,15340.616256,1002.201092,1.086016,1.117339,0.203899,0.213940,0.203474,1.800000,1683.000000,0.004280
2719,3612,16131-3120-35,68479802,158,540,3,2018,L,16131,35,...,1342.511183,610.997030,1.135949,0.983250,0.097918,0.085386,0.111536,30.938140,16706.595579,0.000996
2628,2267,14111-7761-96,391159180,187,1635,3,2018,L,14111,96,...,6933.240200,310.626607,1.004088,0.978766,0.120026,0.131777,0.109875,16.590211,27124.994252,0.005429

In [54]:
def aleatorio_sin_rep(n, max_mz):
    rnd = rd.randint(1, max_mz)
    while rnd == n:
        rnd = rd.randint(1, max_mz)
    return rnd

no_elecc = 3

ciudad_cols = ['cell', 'CMN_MZ_PR', 'Avaluo', 'Sup_Lineas', 'Sup_Predial','Calidad','Código de destino', 'Año',
                'M2_Predios', 'M2_Pobla',
            'acc_lc', 'acc_lh', 'acc_li', 'acc_log10',  'acc_lof','acc_pc', 'acc_ph', 'acc_pi', 'acc_pl',
                'Dist_Cent', 'Dist_Metro', 'Dist_Auto', 'Dist_PGV', 'Dist_PSA','D_Pre_Com', 'D_Lin_Com', 'Dist_Tren',
                         'uf2018','valor_prop','Ratio_Pre']
                   
for i in range(1, no_elecc+1):
    bd_localizaciones_L[f'cell_not_{i}'] = bd_localizaciones_L.apply(lambda row: aleatorio_sin_rep(row['cell'], max_mz), axis = 1)
    bd_localizaciones_L = bd_localizaciones_L.join(bd_localizaciones[ciudad_cols].set_index('cell'), on= f'cell_not_{i}', rsuffix= f'_not_{i}')
    
    #bd_localizaciones_L[f'cell_not_{i}'] = bd_localizaciones_L.apply(lambda row: aleatorio_sin_rep(row['cell'], max_mz), axis = 1)
    #bd_localizaciones_L = bd_localizaciones_L.join(bd_localizaciones[ciudad_cols].set_index('cell'), on= f'cell_not_{i}', rsuffix= f'_not_{i}')
   
    #bd_localizaciones[f'cell_not_{i}'] = bd_localizaciones.apply(lambda row: aleatorio_sin_rep(row['cell'], max_mz), axis = 1)
    #bd_localizaciones = bd_localizaciones.join(ciudad[ciudad_cols].set_index('cell'), on= f'cell_not_{i}', rsuffix= f'_not_{i}')
    
bd_localizaciones_L['choice'] = 0

TypeError: can only concatenate str (not "int") to str

In [ ]:
display(bd_localizaciones_L)

In [ ]:
import biogeme.database as db
import biogeme.biogeme as bio
import biogeme.models as models
import biogeme.results as res
from biogeme.expressions import Beta, DefineVariable, bioDraws, log, MonteCarlo

In [ ]:
bd_localizaciones_L.columns

# Estimación Modelo

In [ ]:
bd_choice = bd_localizaciones_L.copy()

In [ ]:
bd_choice.columns

In [ ]:
bd_choice = bd_choice.dropna()

In [ ]:
bd_choice.isnull().values.any()

In [ ]:
bd_choice = bd_choice[['cell','Avaluo', 'Sup_Lineas', 'Sup_Predial','Calidad','Año','M2_Predios', 'M2_Pobla',
                         'acc_lc', 'acc_lh', 'acc_li', 'acc_log10',  'acc_lof','acc_pc', 'acc_ph', 'acc_pi', 'acc_pl',
                    'Dist_Cent', 'Dist_Metro', 'Dist_Auto', 'Dist_PGV', 'Dist_PSA','D_Pre_Com', 'D_Lin_Com', 'Dist_Tren',
                         'uf2018','valor_prop','Ratio_Pre',
                       
'cell_not_1','Avaluo_not_1', 'Sup_Lineas_not_1', 'Sup_Predial_not_1','Calidad_not_1', 'Año_not_1',
                       'M2_Predios_not_1', 'M2_Pobla_not_1',
                         'acc_lc_not_1', 'acc_lh_not_1', 'acc_li_not_1', 'acc_log10_not_1',  'acc_lof_not_1',
                       'acc_pc_not_1', 'acc_ph_not_1', 'acc_pi_not_1', 'acc_pl_not_1',
                         'Dist_Cent_not_1', 'Dist_Metro_not_1', 'Dist_Auto_not_1', 'Dist_PGV_not_1',
                       'Dist_PSA_not_1','D_Pre_Com_not_1', 'D_Lin_Com_not_1','Dist_Tren_not_1',
                       'uf2018_not_1','valor_prop_not_1','Ratio_Pre_not_1',
                       
'cell_not_2','Avaluo_not_2', 'Sup_Lineas_not_2', 'Sup_Predial_not_2','Calidad_not_2', 'Año_not_2',
                       'M2_Predios_not_2', 'M2_Pobla_not_2',
                         'acc_lc_not_2', 'acc_lh_not_2', 'acc_li_not_2', 'acc_log10_not_2',  'acc_lof_not_2',
                       'acc_pc_not_2', 'acc_ph_not_2', 'acc_pi_not_2', 'acc_pl_not_2',
                        'Dist_Cent_not_2', 'Dist_Metro_not_2', 'Dist_Auto_not_2', 'Dist_PGV_not_2',
                       'Dist_PSA_not_2','D_Pre_Com_not_2', 'D_Lin_Com_not_2','Dist_Tren_not_2',
                       'uf2018_not_2','valor_prop_not_2','Ratio_Pre_not_2',
                       
'cell_not_3','Avaluo_not_3', 'Sup_Lineas_not_3', 'Sup_Predial_not_3','Calidad_not_3','Año_not_3',
                       'M2_Predios_not_3', 'M2_Pobla_not_3',
                         'acc_lc_not_3', 'acc_lh_not_3', 'acc_li_not_3', 'acc_log10_not_3',  'acc_lof_not_3',
                       'acc_pc_not_3', 'acc_ph_not_3', 'acc_pi_not_3', 'acc_pl_not_3',
                         'Dist_Cent_not_3', 'Dist_Metro_not_3', 'Dist_Auto_not_3', 'Dist_PGV_not_3',
                       'Dist_PSA_not_3','D_Pre_Com_not_3', 'D_Lin_Com_not_3','Dist_Tren_not_3',
                       'uf2018_not_3','valor_prop_not_3','Ratio_Pre_not_3',
                       
#'cell_not_4','Avaluo_not_4', 'Sup_Lineas_not_4', 'Sup_Predial_not_4','Calidad_not_4','Año_not_4',
#                       'M2_Predios_not_4', 'M2_Pobla_not_4',
#                         'acc_lc_not_4', 'acc_lh_not_4', 'acc_li_not_4', 'acc_log10_not_4',  'acc_lof_not_4',
#                       'acc_pc_not_4', 'acc_ph_not_4', 'acc_pi_not_4', 'acc_pl_not_4',
#                       'Dist_Cent_not_4', 'Dist_Metro_not_4', 'Dist_Auto_not_4', 'Dist_PGV_not_4',
#                       'Dist_PSA_not_4','D_Pre_Com_not_4', 'D_Lin_Com_not_4','Dist_Tren_not_4',
#                       'uf2018_not_4','valor_prop_not_4','Ratio_Pre_not_4',
#                       
#'cell_not_5','Avaluo_not_5', 'Sup_Lineas_not_5', 'Sup_Predial_not_5','Calidad_not_5','Año_not_5',
#                       'M2_Predios_not_5', 'M2_Pobla_not_5',
#                         'acc_lc_not_5', 'acc_lh_not_5', 'acc_li_not_5', 'acc_log10_not_5',  'acc_lof_not_5',
#                       'acc_pc_not_5', 'acc_ph_not_5', 'acc_pi_not_5', 'acc_pl_not_5',
#                     'Dist_Cent_not_5', 'Dist_Metro_not_5', 'Dist_Auto_not_5', 'Dist_PGV_not_5',
#                       'Dist_PSA_not_5','D_Pre_Com_not_5', 'D_Lin_Com_not_5','Dist_Tren_not_5',
#                      'uf2018_not_5','valor_prop_not_5','Ratio_Pre_not_5',
#'cell_not_6','Avaluo_not_6', 'Sup_Lineas_not_6', 'Sup_Predial_not_6','Calidad_not_6','Año_not_6',
#                       'M2_Predios_not_6', 'M2_Pobla_not_6',
#                        'acc_lc_not_6', 'acc_lh_not_6', 'acc_li_not_6', 'acc_log10_not_6',  'acc_lof_not_6',
 #                      'acc_pc_not_6', 'acc_ph_not_6', 'acc_pi_not_6', 'acc_pl_not_6',
  #                       'Dist_Cent_not_6', 'Dist_Metro_not_6', 'Dist_Auto_not_6', 'Dist_PGV_not_6',
#                      'Dist_PSA_not_6','D_Pre_Com_not_6', 'D_Lin_Com_not_6','Dist_Tren_not_6',
#                       'uf2018_not_6','valor_prop_not_6','Ratio_Pre_not_6',
#                       
#'cell_not_7','Avaluo_not_7', 'Sup_Lineas_not_7', 'Sup_Predial_not_7','Calidad_not_7', 'Año_not_7',
#                       'M2_Predios_not_7', 'M2_Pobla_not_7',
#                         'acc_lc_not_7', 'acc_lh_not_7', 'acc_li_not_7', 'acc_log10_not_7',  'acc_lof_not_7',
#                       'acc_pc_not_7', 'acc_ph_not_7', 'acc_pi_not_7', 'acc_pl_not_7',
#                        'Dist_Cent_not_7', 'Dist_Metro_not_7', 'Dist_Auto_not_7', 'Dist_PGV_not_7',
#                       'Dist_PSA_not_7','D_Pre_Com_not_7', 'D_Lin_Com_not_7','Dist_Tren_not_7',
#                       'uf2018_not_7','valor_prop_not_7','Ratio_Pre_not_7',
#                       
#'cell_not_8','Avaluo_not_8', 'Sup_Lineas_not_8', 'Sup_Predial_not_8','Calidad_not_8','Año_not_8',
#                       'M2_Predios_not_8', 'M2_Pobla_not_8',
#                         'acc_lc_not_8', 'acc_lh_not_8', 'acc_li_not_8', 'acc_log10_not_8',  'acc_lof_not_8',
#                       'acc_pc_not_8', 'acc_ph_not_8', 'acc_pi_not_8', 'acc_pl_not_8',
#                         'Dist_Cent_not_8', 'Dist_Metro_not_8', 'Dist_Auto_not_8', 'Dist_PGV_not_8',
#                       'Dist_PSA_not_8','D_Pre_Com_not_8', 'D_Lin_Com_not_8','Dist_Tren_not_8',
#                       'uf2018_not_8','valor_prop_not_8','Ratio_Pre_not_8',
#
#'cell_not_9','Avaluo_not_9', 'Sup_Lineas_not_9', 'Sup_Predial_not_9','Calidad_not_9', 'Año_not_9',
#                       'M2_Predios_not_9', 'M2_Pobla_not_9',
#                         'acc_lc_not_9', 'acc_lh_not_9', 'acc_li_not_9', 'acc_log10_not_9',  'acc_lof_not_9',
#                       'acc_pc_not_9', 'acc_ph_not_9', 'acc_pi_not_9', 'acc_pl_not_9',
#                        'Dist_Cent_not_9', 'Dist_Metro_not_9', 'Dist_Auto_not_9', 'Dist_PGV_not_9',
#                       'Dist_PSA_not_9','D_Pre_Com_not_9', 'D_Lin_Com_not_9','Dist_Tren_not_9',
#                     'uf2018_not_9','valor_prop_not_9','Ratio_Pre_not_9',
                       'choice']]

In [ ]:
#bd_choice.to_csv('bd_choice.csv')

In [ ]:
database = db.Database("Modelo Choice", bd_choice)
globals().update(database.variables)
database.getSampleSize()

In [ ]:
xh = ['Ratio_Pre'] #Carecteristicas del predio escogido
zi = ['acc_log10', #'acc_lc','acc_lh', 'acc_li', #'acc_lof',
      'acc_pc','acc_pi', #'acc_ph', 'acc_pl',
      'Dist_Auto', 'Dist_PGV', 'Dist_PSA','Dist_Metro'] #Atributos  'Dist_Cent','D_Lin_Com', 'Dist_Tren','D_Pre_Com' ,
ri = ['valor_prop'] #Renta
total_vars = xh + zi + ri

In [ ]:
betas = {}
for v in total_vars:
    auxBeta = Beta(f'B_{v}',0,-100,100,0)
    betas.update({f'B_{v}': auxBeta})

In [ ]:
betas

In [ ]:
#Funciones de Utilidad
V_choice = 0
for v in total_vars:
    V_choice += betas['B_{}'.format(v)]*database.variables[v]
    
V = {0: V_choice}
av = {0:1}

V_nochoice = []
for i in range(1, no_elecc+1):
    V_nochoice_aux = 0
    for v in xh:
        V_nochoice_aux += betas['B_{}'.format(v)]*database.variables[v]
    for v in zi:
        V_nochoice_aux += betas['B_{}'.format(v)]*database.variables['{}_not_{}'.format(v,i)]
    for v in ri:
        V_nochoice_aux += betas['B_{}'.format(v)]*database.variables['{}_not_{}'.format(v,i)]
    
    V.update({i: V_nochoice_aux})
    av.update({i:1})

In [ ]:
logprob = models.loglogit(V, av, choice) #multinomial
#bio.WEIGHT = 'Sup_Predial'
biogeme  = bio.BIOGEME(database,logprob)
biogeme.modelName = "choice"
results = biogeme.estimate()

In [ ]:
pandasResults = results.getEstimatedParameters()
pandasResults

In [ ]:
pandasCorrelations = results.getCorrelationResults()
pandasCorrelations

In [ ]:
pandasGeneralStat = results.getGeneralStatistics()
pandasGeneralStat